import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import ClientLayout from "./client-layout/page"; // Importujemy klientowy layout
import "./globals.css";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ClientLayout>{children}</ClientLayout>
    </ClerkProvider>
  );
}
